apiVersion: apps/v1
kind: Deployment
metadata:
  name: faq-backend
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: faq-backend
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "staging"
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: JVM_OPTS
          value: "-Xms256m -Xmx512m -XX:+UseG1GC"
        - name: ACTUATOR_ENDPOINTS_ENABLED
          value: "true"
        - name: METRICS_EXPORT_ENABLED
          value: "true"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: faq-backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/actuator/prometheus"
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: metrics
    port: 9090
    targetPort: 8080