apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: redis
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: REDIS_MAXMEMORY
          value: "100mb"
        - name: REDIS_MAXMEMORY_POLICY
          value: "allkeys-lru"
        - name: REDIS_DATABASES
          value: "16"
        - name: REDIS_SAVE
          value: "900 1 300 10 60 10000"
        - name: REDIS_LOGLEVEL
          value: "notice"
        command:
        - redis-server
        - --requirepass
        - $(REDIS_PASSWORD)
        - --maxmemory
        - $(REDIS_MAXMEMORY)
        - --maxmemory-policy
        - $(REDIS_MAXMEMORY_POLICY)
        - --databases
        - $(REDIS_DATABASES)
        - --save
        - $(REDIS_SAVE)
        - --loglevel
        - $(REDIS_LOGLEVEL)
        - --appendonly
        - "yes"
        - --appendfsync
        - "everysec"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard